Repository toolatebro/TakenSeat, pull requests merged in 2025-04, with the labels that each got.

#5 #4 <Eureka> @EnableEurekaServer 어노테이션 추가 및 yml 작성.
  com.taken_seat.eureka-service/.gitignore
  com.taken_seat.eureka-service/src/main/java/com/taken_seat/eureka_service/EurekaServiceApplication.java
  com.taken_seat.eureka-service/src/main/resources/application.properties
Labels: enhancement

#27 #20 <Gateway> JWT 의존성 및 JwtUtil 클래스 추가
  com.taken_seat.gateway-service/build.gradle
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/util/JwtUtil.java
Labels: ❣feat

#47 #41 <Performance> 공연 도메인 Entity 구현
  .gitignore
  com.taken_seat.performance-service/.gitignore
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceSchedule.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceScheduleStatus.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceSeatPrice.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceStatus.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/Seat.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/SeatStatus.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/SeatType.java
  com.taken_seat.performance-service/src/main/resources/application.properties
Labels: ❣feat, 🕹️ chore

#48 #12 <Payment> 결제 Entity 구현 및 create 기능 구현
  com.taken_seat.payment-service/.gitignore
  com.taken_seat.payment-service/build.gradle
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/request/PaymentRegisterReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/response/PaymentRegisterResDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/enums/PaymentStatus.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/PaymentHistory.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentHistoryRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/JpaPaymentHistoryRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/JpaPaymentRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/main/resources/application.properties
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/PaymentServiceApplicationTests.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
Labels: ❣feat, 🕹️ chore

#49 #43 Auth 회원가입 기능
  com.taken_seat.auth-service/.gitignore
  com.taken_seat.auth-service/build.gradle
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthSignUpDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthSignUpResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/User.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/user/UserRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/vo/Role.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/persistence/user/UserRepositoryImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/security/WebSecurityConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/auth/AuthController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/auth/AuthSignUpRequestDto.java
  com.taken_seat.auth-service/src/main/resources/application.properties
Labels: ❣feat

#50 #18 <Payment> 단건 Read 조회 기능 구현
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/exception/PaymentNotFoundException.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/response/PaymentDetailResDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
Labels: ❣feat, 🌼 test

#51 #44 Auth 로그인 기능
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthLoginDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthLoginResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/security/WebSecurityConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/util/JwtUtil.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/auth/AuthController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/auth/AuthLoginRequestDto.java
Labels: ❣feat

#55 #29 <Performance> 공연 생성 API 구현
  .gitignore
  com.taken_seat.eureka-service/.gitignore
  com.taken_seat.eureka-service/src/main/java/com/taken_seat/eureka_service/EurekaServiceApplication.java
  com.taken_seat.eureka-service/src/main/resources/application.properties
  com.taken_seat.gateway-service/.gitignore
  com.taken_seat.gateway-service/build.gradle
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/filter/JwtAuthenticationFilter.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/util/JwtUtil.java
  com.taken_seat.gateway-service/src/main/resources/application.properties
  com.taken_seat.payment-service/.gitignore
  com.taken_seat.payment-service/build.gradle
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/request/PaymentRegisterReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/response/PaymentRegisterResDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/enums/PaymentStatus.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/PaymentHistory.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentHistoryRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/JpaPaymentHistoryRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/JpaPaymentRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/main/resources/application.properties
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/PaymentServiceApplicationTests.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
  com.taken_seat.performance-service/.gitignore
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/RequestMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/ResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/CreatePerformanceScheduleDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/CreateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/CreateSeatPriceDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/CreatePerformanceScheduleResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/CreateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/CreateSeatPriceResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceSchedule.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceScheduleStatus.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceSeatPrice.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceStatus.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/Seat.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/SeatStatus.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/SeatType.java
  com.taken_seat.performance-service/src/main/resources/application.properties
  com.taken_seat.performance-service/src/test/java/com/taken_seat/performance_service/performance/application/service/PerformanceServiceTest.java
Labels: ❣feat, 🌼 test

#54 #45 Auth 유저 조회기능
  com.taken_seat.auth-service/build.gradle
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/PageResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/UserInfoResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/mileage/Mileage.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/User.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/UserCoupon.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/UserCouponId.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/user/UserQueryRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/user/UserRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/userCoupon/UserCouponRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/QuerydslConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/persistence/user/UserQueryRepositoryImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/persistence/userCoupon/UserCouponRepositoryImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
Labels: ❣feat

#59 #58 Auth 로그인 시 헤더에 token값 담아서 반환
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/util/JwtUtil.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/auth/AuthController.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/util/JwtUtil.java
Labels: 🩹 fix

#56 #23 <Booking> 예매 Create 기능
  com.taken_seat.booking-service/.gitignore
  com.taken_seat.booking-service/build.gradle
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/BookingServiceApplication.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/application/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/application/RedissonService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/application/dto/request/BookingCreateRequest.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/application/dto/response/BookingCreateResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/domain/Booking.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/domain/BookingStatus.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/domain/repository/BookingRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/infrastructure/service/RedissonServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/presentation/BookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/common/BaseEntity.java
  com.taken_seat.booking-service/src/main/resources/application.properties
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/BookingServiceApplicationTests.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/infrastructure/service/BookingServiceTest.java
Labels: ❣feat, 🌼 test

#60 #34 <Performance> 공연 삭제 API 구현
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/test/java/com/taken_seat/performance_service/performance/application/service/PerformanceServiceTest.java
Labels: ❣feat, 🌼 test

#61 #21 <Payment> soft delete 기능 구현 및 테스트 코드 작성
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
Labels: ❣feat, 🌼 test

#63 #62 Auth 유저 정보 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/UserUpdateDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/User.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/user/UserUpdateRequestDto.java
Labels: ❣feat

#75 #29 <Performance> 공연 생성 API 구현
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/RequestMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/ResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/CreatePerformanceScheduleDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/CreateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/CreateSeatPriceDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/CreatePerformanceScheduleResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/CreateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/CreateSeatPriceResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceSchedule.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceScheduleStatus.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceStatus.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/Seat.java
  com.taken_seat.performance-service/src/test/java/com/taken_seat/performance_service/performance/application/service/PerformanceServiceTest.java
Labels: ❣feat, 🌼 test

#82 #24 <Booking> 예매 조회 API 구현
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/application/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/application/dto/response/BookingPageResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/application/dto/response/BookingReadResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/domain/repository/BookingRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/presentation/BookingController.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/infrastructure/service/BookingServiceTest.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/infrastructure/service/ConcurrencyTest.java
Labels: ❣feat, 🌼 test

#81 #80 Auth Role 체킹 기능 구현
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/mileage/UserMileageDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/mileage/UserMileageResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/mileage/Mileage.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/mileage/MileageRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/persistence/mileage/MileageRepositoryImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/mileage/MileageController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/mileage/CreateUserMileageRequestDto.java
Labels: ♻️ refactor

#85 #84 <Booking> 예매 취소 기능
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/application/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/domain/Booking.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/presentation/BookingController.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/infrastructure/service/BookingServiceTest.java
Labels: ❣feat, 🌼 test

#86 #83 <Payment> Redis Caching 설정 및 PaymentService Caching 기능 구현
  com.taken_seat.payment-service/build.gradle
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/redis/RedisCachingConfig.java
Labels: ❣feat

#88 #68 Mileage Read 기능 구현
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/mileage/UserMileageResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/mileage/MileageQueryRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/mileage/MileageRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/persistence/mileage/MileageQueryRepositoryImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/mileage/MileageController.java
Labels: ❣feat

#97 #96 Mileage 히스토리 검색 기능
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/mileage/MileageRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/mileage/MileageController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/mileage/UserMileageRequestDto.java
Labels: ❣feat

#105 #31 <Performance> 공연 전체 조회 API
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/ResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/SearchFilterParam.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/PageResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/SearchResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/spec/PerformanceSpecification.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
Labels: ❣feat

#107 #95 <Booking> 예매 사용자 검증기능 및 어드민 조회기능
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/application/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/RedissonService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/request/BookingCreateRequest.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/response/AdminBookingPageResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/response/AdminBookingReadResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/response/BookingCreateResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/response/BookingPageResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/response/BookingReadResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/Booking.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/BookingStatus.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BookingRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/RedissonServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/AdminBookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/BaseEntity.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/CustomUser.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/CustomUserArgumentResolver.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/WebConfig.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/presentation/BookingController.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/infrastructure/service/BookingServiceTest.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/infrastructure/service/ConcurrencyTest.java
Labels: ❣feat, 🌼 test

#106 #101 Coupon Create 기능 구현
  com.taken_seat.coupon-service/.gitignore
  com.taken_seat.coupon-service/build.gradle
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/CouponDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/CouponResponseDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/CouponService.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/entity/Coupon.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/repository/CouponRepository.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/persistence/CouponRepositoryImpl.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/CouponController.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/dto/CreateCouponRequestDto.java
  com.taken_seat.coupon-service/src/main/resources/application.properties
Labels: ❣feat

#111 #102 Coupon Read 기능 개발
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/PageResponseDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/CouponService.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/repository/CouponQueryRepository.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/QuerydslConfig.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/persistence/CouponQueryRepositoryImpl.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/CouponController.java
Labels: ❣feat

#122 #35 <Performance> 공연장 생성 API
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/mapper/HallRequestMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/mapper/HallResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/request/CreateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/request/CreateSeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/CreateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/SeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/Seat.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/controller/PerformanceHallController.java
Labels: ❣feat

#113 #103 Coupon Update 기능 개발
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/CouponUpdateDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/CouponService.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/entity/Coupon.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/repository/CouponRepository.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/persistence/CouponQueryRepositoryImpl.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/CouponController.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/dto/UpdateCouponRequestDto.java
Labels: ♻️ refactor, ❣feat

#112 #87 <Common> 공동 반환 통일을 위한 DTO 구현 및 GlobalException 핸들러 구현
  com.taken_seat.auth-service/build.gradle
  com.taken_seat.auth-service/settings.gradle
  com.taken_seat.booking-service/build.gradle
  com.taken_seat.booking-service/settings.gradle
  com.taken_seat.common-service/build.gradle
  com.taken_seat.common-service/settings.gradle
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/ApiResponseData.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/entity/BaseTimeEntity.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/BaseException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/PaymentNotFoundException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/handler/GlobalExceptionHandler.java
  com.taken_seat.coupon-service/build.gradle
  com.taken_seat.coupon-service/settings.gradle
  com.taken_seat.eureka-service/settings.gradle
  com.taken_seat.gateway-service/settings.gradle
  com.taken_seat.payment-service/build.gradle
  com.taken_seat.payment-service/settings.gradle
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/PaymentServiceApplication.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/exception/PaymentNotFoundException.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/PaymentHistory.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/settings.gradle
  com.taken_seat.queue-service/build.gradle
  com.taken_seat.queue-service/settings.gradle
  com.taken_seat.review-service/build.gradle
  com.taken_seat.review-service/settings.gradle
Labels: ❣feat

#131 #36 <Performance> 공연장 상세 조회 API
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/mapper/HallResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/DetailResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/controller/PerformanceHallController.java
Labels: ❣feat

#133 #128 Auth Common 적용
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/User.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/auth/AuthController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
Labels: ♻️ refactor

#138 #137 Common application.properties 애플리케이션 이름 제거
  com.taken_seat.common-service/src/main/resources/application.properties
Labels: 🩹 fix

#135 #91 <Booking> Ticket 생성 기능 추가
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/Booking.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/dto/request/TicketCreateRequest.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/dto/response/TicketCreateResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/messaging/TicketProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/service/TicketService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/domain/Ticket.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/domain/repository/TicketRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/client/PerformanceClient.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/messaging/TicketConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/service/TicketServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/presentation/TicketController.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/request/TicketPerformanceClientRequest.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/response/TicketPerformanceClientResponse.java
Labels: ❣feat

#139 #132 Payment Common 적용과 동시에 모든 기능 리팩터링
  com.taken_seat.common-service/.gitignore
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/PaymentHistoryNotFoundException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/enums/PaymentStatus.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/PaymentHistory.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentHistoryRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
Labels: ♻️ refactor, ❣feat, 🌼 test

#144 #142 <Common> Argument Resolver 등록
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/BookingServiceApplication.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/AdminBookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/service/TicketService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/messaging/TicketConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/service/TicketServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/presentation/TicketController.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/infrastructure/service/ConcurrencyTest.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/component/CustomUserArgumentResolver.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/config/WebConfig.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/AuthenticatedUser.java
Labels: ❣feat

#150 #149 <Performance> 공연 티켓 발행 정보 API 구현
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/request/TicketPerformanceClientRequest.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/response/TicketPerformanceClientResponse.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performenceticket/application/dto/mapper/RequestMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performenceticket/application/service/PerformenceTicketService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performenceticket/presentation/controller/PerformenceTicketController.java
Labels: ❣feat

#155 #154 <Performance> 공연 티켓 조회 API 공연 아이디 추가
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/request/TicketPerformanceClientRequest.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performenceticket/application/dto/mapper/RequestMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performenceticket/application/service/PerformenceTicketService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performenceticket/presentation/controller/PerformenceTicketController.java
Labels: ❣feat

#157 #156 Auth 100개 유저 데이터 생성
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/KafkaUserInfoMessage.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/KafkaProducerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/UserCoupon.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/UserCouponId.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/kafka/KafkaConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/query/QuerydslConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/redis/RedisCacheConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/security/WebSecurityConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/util/DataInitializer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaProducerController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/user/KafkaUserCouponRequestMessage.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/query/QuerydslConfig.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/redis/RedisCacheConfig.java
Labels: ♻️ refactor, ❣feat

#158 #151 <Performance> 공연 종료 시간 조회 API 구현
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/PerformanceEndTimeDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
Labels: ❣feat

#159 #23 <Booking> 클라이언트 메서드 추가 및 공통 예외 처리
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/BookingClientService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/RedissonService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/request/BookingCreateRequest.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/Booking.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BookingAdminRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BookingRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingAdminJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingAdminRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingClientServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/RedissonServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/AdminBookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingClientController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/service/TicketService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/messaging/TicketConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/service/TicketServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/presentation/TicketController.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/infrastructure/service/BookingServiceTest.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/infrastructure/service/ConcurrencyTest.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/ApiResponseData.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/response/BookingStatusDto.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/BookingException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
Labels: ❣feat, 🌼 test

#147 #92 <Booking> 티켓 조회 기능 추가
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/dto/response/TicketPageResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/dto/response/TicketReadResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/service/TicketService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/domain/repository/TicketRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/service/TicketServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/presentation/TicketController.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceTest.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/booking/infrastructure/service/ConcurrencyTest.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/ticket/infrastructure/service/TicketServiceTest.java
Labels: ❣feat, 🌼 test

#165 #39 <Performance> 공연장 삭제 API
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/controller/PerformanceHallController.java
Labels: ❣feat

#170 #168 <Common> Kafka 공통 설정 추가
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingClientService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingEventProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/RedissonService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingClientServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/RedissonServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/AdminBookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingClientController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/messaging/TicketProducer.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/booking/infrastructure/service/ConcurrencyTest.java
  com.taken_seat.common-service/build.gradle
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/component/GenericJsonDeserializer.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/component/GenericJsonSerializer.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/config/KafkaConfig.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/event/BookingCreatedEvent.java
Labels: ❣feat

#179 #171 Kafka 기본 세팅 수정사항 최종본 및 메시지 producer, consumer 예시 입니다.
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/AuthServiceApplication.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/KafkaUserInfoMessage.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/KafkaProducerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/kafka/GenericJsonDeserializer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/kafka/GenericJsonSerializer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/kafka/KafkaConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaProducerController.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/component/GenericJsonDeserializer.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/component/GenericJsonSerializer.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/config/KafkaConfig.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/KafkaUserInfoMessage.java
  com.taken_seat.common-service/src/main/resources/application.properties
  com.taken_seat.coupon-service/build.gradle
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/CouponServiceApplication.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/kafka/GenericJsonDeserializer.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/kafka/GenericJsonSerializer.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/kafka/KafkaConfig.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/KafkaConsumer.java
Labels: ♻️ refactor

#182 #181 각 도메인에 BaseEntity 메서드 적용 로직을 깔끔하게 정돈했습니다.
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/mileage/Mileage.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/User.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/CouponService.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/entity/Coupon.java
Labels: ♻️ refactor

#180 #127 <Review> 좋아요 수 토글 기능
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/entity/BaseTimeEntity.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/ReviewServiceApplication.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewLikeScheduler.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewLikeService.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewService.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/model/Review.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/model/ReviewLike.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/ReviewLikeRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/ReviewRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/config/redis/RedisTemplateConfig.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/JpaReviewLikeRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/service/ReviewLikeServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/service/ReviewServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/presentation/controller/ReviewController.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewLikeServiceTest.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewServicesTest.java
Labels: ❣feat, 🌼 test

#184 #183 Coupon sendTo 메서드를 사용해서 받은 메시지에 대한 응답을 auth-service로 전달
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/KafkaProducerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaConsumer.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/config/KafkaConfig.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/KafkaUserInfoMessage.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/KafkaProducerService.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/KafkaConsumer.java
Labels: ❣feat

#186 #173 <Performance> 공연장 CRUD 리팩토링
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/CreateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/DetailResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/PerformanceScheduleResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/SearchResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/UpdateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/helper/PerformanceCreateHelper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/request/BaseSeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/request/CreateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/request/CreateSeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/request/UpdateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/request/UpdateSeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/helper/PerformanceHallCreateHelper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/validation/PerformanceHallValidator.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/controller/PerformanceHallController.java
Labels: ♻️ refactor, ❣feat

#187 #185 <Paymeny> 중간 리팩터링
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/PaymentException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/PaymentHistoryException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/PaymentHistoryNotFoundException.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/PaymentServiceApplication.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/response/PaymentDetailResDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentQuerydslRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/config/querydsl/QueryDslConfig.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/config/redis/RedisCachingConfig.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/PaymentQuerydslRepositoryImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/service/PaymentServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewLikeServiceTest.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewServicesTest.java
Labels: ♻️ refactor, 🌼 test

#189 #167 <Performance> 좌석 선점 및 선점 취소 API 구현
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/request/BookingSeatClientRequestDto.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/response/BookingSeatClientResponseDto.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/Seat.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/controller/PerformanceHallController.java
Labels: ❣feat

#194 #190 예매 결제 이벤트 공통 메시지DTO 구현
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentRequestMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentResultMessage.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/BookingEventListener.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/BookingEventProducer.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentServiceImpl.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
Labels: ❣feat

#195 #190 예매 결제 이벤트 공통 메시지DTO 구현
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentRequestMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentResultMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/enums/PaymentResultStatus.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
Labels: ❣feat

#196 #32 <Performance> 공연 및 공연 회차 상태 변경 API
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/helper/PerformanceCreateHelper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceSchedule.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceScheduleStatus.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
Labels: ❣feat

#193 #188 <Coupon> 쿠폰 발행한 유저의 데이터베이스에 요청한 쿠폰 데이터 저장
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/KafkaProducerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/KafkaService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/UserCoupon.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/userCoupon/UserCouponRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/redis/RedisCacheConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaProducerController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/CouponException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/KafkaUserInfoMessage.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/CouponDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/CouponResponseDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/CouponUpdateDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/KafkaProducerService.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/entity/Coupon.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/redis/RedisTemplateConfig.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/KafkaConsumer.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/dto/CreateCouponRequestDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/dto/UpdateCouponRequestDto.java
  com.taken_seat.coupon-service/src/main/resources/db/data.sql
Labels: ❣feat

#199 #198 Auth Payment 와 상호작용할 메시지 객체 생성 및 Exception 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/mileage/Mileage.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/mileage/MileageController.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/AuthException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/MileageException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/UserBenefitMessage.java
Labels: ♻️ refactor, ❣feat

#202 #200 Auth 결제 도메인과 주고받을 메시지 객체에 paymentId 추가
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/UserBenefitMessage.java
Labels: ♻️ refactor

#201 feat : #191 결제 요청 리스너 구현 및 결과 반환 프로듀서 구현
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentRequestMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentResultMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/UserBenefitMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/enums/PaymentResultStatus.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/BookingEventListener.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/consumer/PaymentRequestListener.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/producer/PaymentResultProducer.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/producer/UserBenefitRequestProducer.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentEventHandlerService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/enums/PaymentStatus.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/PaymentHistory.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/consumer/PaymentRequestListenerImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/producer/PaymentResultProducerImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/producer/UserBenefitRequestProducerImpl.java
Labels: ❣feat

#206 #203 <Payment> 마일리지 차감 및 쿠폰 사용 요청 결과 반환 리스너 구현
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/consumer/UserBenefitResultListener.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/UserBenefitEventHandlerService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/UserBenefitEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/consumer/UserBenefitResultListenerImpl.java
Labels: ❣feat

#209 #207 <Payment> 결제 이벤트 처리 과정에서 누락된 코드들을 추가했습니다.
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/KafkaProducerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/mileage/MileageRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/UserBenefitEventHandlerServiceImpl.java
Labels: 🩹 fix

#210 #208 Auth kafka Producer 기존의 GetMapping을 PostMapping 으로 변경
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaProducerController.java
Labels: 🩹 fix

#211 #207 <Payment> 결제 이벤트 진행중에 히스토리 업데이트 메서드 수정 및 추가
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/UserBenefitEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/PaymentHistory.java
Labels: 🩹 fix

#216 #215 <Payment> 결제 도메인에서 마일리지 쿠폰 차감 책임을 분리
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingConsumer.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentRequestMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentResultMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/enums/PaymentResultStatus.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/consumer/PaymentRequestListener.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/consumer/UserBenefitResultListener.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/producer/PaymentResultProducer.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/producer/UserBenefitRequestProducer.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentEventHandlerService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/UserBenefitEventHandlerService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/UserBenefitEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/consumer/PaymentRequestListenerImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/consumer/UserBenefitResultListenerImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/producer/PaymentResultProducerImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/producer/UserBenefitRequestProducerImpl.java
Labels: 🩹 fix, ♻️ refactor, ❣feat

#219 #197 <Monitoring> 시스템 모니터링 기반 구축
  com.taken_seat.common-service/build.gradle
  com.taken_seat.common-service/docker-compose.common.yml
  com.taken_seat.common-service/prometheus/prometheus.yml
  com.taken_seat.gateway-service/build.gradle
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/src/main/resources/logback-spring.xml
  loki-config.yml
Labels: 🕹️ chore, 👁️monitoring

#214 #213 Auth kafka 성공 유무에 log를 찍었습니다.
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/KafkaProducerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaConsumer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaProducerController.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/UserBenefitMessage.java
Labels: ♻️ refactor

#221 #220 Auth Swagger 기능 추가
  com.taken_seat.auth-service/build.gradle
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/security/WebSecurityConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/auth/AuthController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/mileage/MileageController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/AuthControllerDocs.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/MileageControllerDocs.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/UserControllerDocs.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/filter/SwaggerConfig.java
Labels: ❣feat

#234 #233 Auth 최신 사항 업데이트 입니다.
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/util/DataInitializer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaConsumer.java
  com.taken_seat.coupon-service/src/main/resources/db/data.sql
  com.taken_seat.gateway-service/build.gradle
Labels: ♻️ refactor

#231 Feature/#226
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/QueueServiceApplication.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/application/service/QueueScheduler.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/application/service/QueueService.java
Labels: ❣feat

#238 feat: #235 <Booking> 쿠폰, 마일리지 기록 저장 및 원복처리 요청
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/BenefitUsageHistory.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BenefitUsageHistoryRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BenefitUsageHistoryJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BenefitUsageHistoryRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingConsumer.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
Labels: ❣feat

#239 #237 Auth 보상 트랜잭션 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/KafkaProducerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaConsumer.java
Labels: ♻️ refactor

#242 #241 <Auth> 코드 리팩토링
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/booking/UserToBookingConsumer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/booking/UserToBookingConsumerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/coupon/UserToCouponConsumer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/coupon/UserToCouponConsumerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/coupon/UserToCouponPublisher.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/userCoupon/UserCouponRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/coupon/UserToCouponConsumerImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/coupon/UserToCouponConsumerServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/coupon/UserToCouponPublisherImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/kafka/UserToCouponPublisherController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/mileage/MileageController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/KafkaProducerController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/MileageControllerDocs.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/UserControllerDocs.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/UserToCouponPublisherControllerTest.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/KafkaConsumer.java
Labels: 🩹 fix, ♻️ refactor

#243 #217 <Performance> 공연 모니터링 적용
  com.taken_seat.auth-service/.gitignore
  com.taken_seat.auth-service/build.gradle
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/util/GenerateTokens.java
  com.taken_seat.booking-service/.gitignore
  com.taken_seat.booking-service/build.gradle
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/RedissonServiceImpl.java
  com.taken_seat.booking-service/src/main/resources/logback-spring.xml
  com.taken_seat.performance-service/.gitignore
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallRepositoryImpl.java
Labels: ❣feat, 🕹️ chore, 👁️monitoring

#247 #245 <Coupon> kafka 인터페이스 생성 및 구현체 적용 향후 redisson 적용을 위한 의존성 추가
  com.taken_seat.coupon-service/build.gradle
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/kafka/CouponToUserConsumer.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/kafka/CouponToUserConsumerService.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/CouponService.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/CouponServiceImpl.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/kafka/CouponToUserConsumerImpl.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/kafka/CouponToUserConsumerServiceImpl.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/CouponController.java
Labels: ♻️ refactor

#249 #248 <Coupon> swagger 구현
  com.taken_seat.coupon-service/build.gradle
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/CouponController.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/docs/CouponControllerDocs.java
Labels: ♻️ refactor

#254 #218 <Review> 리뷰 평점 기능 구현
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/request/ReviewRegisterReqDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/request/ReviewUpdateReqDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/response/PageReviewResponseDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/response/ReviewDetailResDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/scheduler/AvgRatingBulkScheduler.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/scheduler/ReviewLikeScheduler.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewLikeServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewService.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/model/Review.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/RedisRatingRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/ReviewQuerydslRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/ReviewRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/RedisRatingRepositoryImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/ReviewQuerydslRepositoryImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/presentation/controller/ReviewController.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewLikeServiceTest.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewServicesTest.java
Labels: ♻️ refactor, ❣feat, 🌼 test

#256 #161 <Booking> 예매 시간제한 도입 및 좌석 선점 취소
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingClientService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/RedisService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/RedissonService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/BenefitUsageHistory.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/Booking.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BookingRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/client/PerformanceClient.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/RedisExpireListener.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingClientServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/RedissonServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/BaseEntity.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/config/RedisConfig.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/config/RedisListenerConfig.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/domain/Ticket.java
  com.taken_seat.common-service/docker-compose.common.yml
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
Labels: ❣feat

#258 #257 <Gateway> log 추가
  com.taken_seat.gateway-service/build.gradle
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/filter/JwtAuthenticationFilter.java
Labels: ♻️ refactor

#259 #218 <Payment> 환불 이벤트 컨슈머 구현 및 환불 이벤트 서비스 구현
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentRefundMessage.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/consumer/PaymentRefundRequestListener.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentRefundEventHandlerService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentRefundEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/PaymentHistory.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/consumer/PaymentRefundRequestListenerImpl.java
Labels: ♻️ refactor, ❣feat

#263 #262 <Gateway> logback 추가
  com.taken_seat.gateway-service/src/main/resources/logback-spring.xml
Labels: ♻️ refactor

#266 #265 <DevOps> Prometheus 설정 개선
  com.taken_seat.common-service/prometheus/prometheus.yml
Labels: 🕹️ chore, 👁️monitoring

#268 #267 <Coupon> loki 기능 추가
  com.taken_seat.coupon-service/build.gradle
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/docs/CouponControllerDocs.java
  com.taken_seat.coupon-service/src/main/resources/logback-spring.xml
Labels: ♻️ refactor

#269 #161 <Booking> 쿠폰, 마일리지 사용 DTO 에 가격 추가
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/response/AdminBookingReadResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/response/BookingReadResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/RedisService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/RedissonService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/BenefitUsageHistory.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/UserBenefitMessage.java
Labels: ♻️ refactor, ❣feat

#271 #270 <Auth> kafka에 @Value 어노테이션 추가해서 topic, groupId 적용
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/security/WebSecurityConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/coupon/UserToCouponConsumerImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/coupon/UserToCouponPublisherImpl.java
Labels: ♻️ refactor

#277 #161 <Booking> 치명적인 오류 수정
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
Labels: 🩹 fix

#278 #264 <Auth> 마일리지 적립 기능 추가
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
Labels: ♻️ refactor

#280 #161 <Booking> FeignClient 충돌 해결 및 Auth 도메인에 결제 완료 전송
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/client/PerformanceClient.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/client/PerformanceClient.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/UserBenefitMessage.java
Labels: 🩹 fix, ❣feat

#282 #281 <Auth> 결제 로직 및 보상 트랜잭션 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/booking/UserToBookingConsumer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/booking/UserToBookingConsumerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
Labels: ♻️ refactor

#286 #285 <Auth> 보상 트랜잭션 로직 오류 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
Labels: 🩹 fix

#287 feat: #240 모니터링 적용
  com.taken_seat.queue-service/build.gradle
  com.taken_seat.queue-service/src/main/resources/logback-spring.xml
Labels: 🕹️ chore, 👁️monitoring

#289 #288 <Auth> 보상 트랜잭션 로직, 환불처리 코드 리팩토링 및 스웨거 설정 추가
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/common/config/SwaggerConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
Labels: ♻️ refactor, ❣feat

#290 #279 프로젝트 CI 지속적인 통합과정 추가
  .github/workflows/deploay.yml
  .gitignore
  com.taken_seat.auth-service/.gitignore
  com.taken_seat.auth-service/build.gradle
  com.taken_seat.auth-service/src/main/resources/application.yml
  com.taken_seat.auth-service/src/main/resources/logback-spring.xml
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/AuthServiceApplicationTests.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/UserToCouponPublisherControllerTest.java
  com.taken_seat.booking-service/.gitignore
  com.taken_seat.booking-service/build.gradle
  com.taken_seat.booking-service/src/main/resources/application.yml
  com.taken_seat.booking-service/src/main/resources/logback-spring.xml
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceTest.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/booking/infrastructure/service/ConcurrencyTest.java
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/ticket/infrastructure/service/TicketServiceTest.java
  com.taken_seat.common-service/.gitignore
  com.taken_seat.common-service/src/main/resources/application.yml
  com.taken_seat.common-service/src/test/java/com/taken_seat/common_service/CommonServiceApplicationTests.java
  com.taken_seat.coupon-service/.gitignore
  com.taken_seat.coupon-service/build.gradle
  com.taken_seat.coupon-service/src/main/resources/application.yml
  com.taken_seat.coupon-service/src/main/resources/logback-spring.xml
  com.taken_seat.coupon-service/src/test/java/com/taken_seat/coupon_service/CouponServiceApplicationTests.java
  com.taken_seat.eureka-service/.gitignore
  com.taken_seat.eureka-service/src/main/resources/application.yml
  com.taken_seat.gateway-service/.gitignore
  com.taken_seat.gateway-service/build.gradle
  com.taken_seat.gateway-service/src/main/resources/application.yml
  com.taken_seat.gateway-service/src/main/resources/logback-spring.xml
  com.taken_seat.gateway-service/src/test/java/com/taken_seat/gateway_service/GatewayServiceApplicationTests.java
  com.taken_seat.payment-service/.gitignore
  com.taken_seat.payment-service/build.gradle
  com.taken_seat.payment-service/src/main/resources/application.yml
  com.taken_seat.performance-service/.gitignore
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/src/main/resources/application.yml
  com.taken_seat.performance-service/src/main/resources/logback-spring.xml
  com.taken_seat.performance-service/src/test/java/com/taken_seat/performance_service/PerformanceServiceApplicationTests.java
  com.taken_seat.queue-service/.gitignore
  com.taken_seat.queue-service/build.gradle
  com.taken_seat.queue-service/src/main/resources/application.yml
  com.taken_seat.queue-service/src/main/resources/logback-spring.xml
  com.taken_seat.queue-service/src/test/java/com/taken_seat/queue_service/QueueServiceApplicationTests.java
  com.taken_seat.review-service/.gitignore
  com.taken_seat.review-service/build.gradle
  com.taken_seat.review-service/src/main/resources/application.yml
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewServicesTest.java
Labels: ❣feat, 🕹️ chore

#293 #291 <Auth> 환불 처리 성공 유무에 따른 메시지 전송
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/booking/UserToBookingConsumer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/booking/UserToBookingConsumerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
  com.taken_seat.gateway-service/src/main/resources/application.yml
Labels: ♻️ refactor

#294 feat: #292 yml 파일 수정
  com.taken_seat.queue-service/src/main/resources/application.yml
Labels: 🕹️ chore

#299 #161 <Booking> yml 수정 및 예매 환불기능추가
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingController.java
  com.taken_seat.booking-service/src/main/resources/application.yml
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
Labels: ❣feat

#301 #300 <Payment> 공통 로그 네이밍 적용
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentRefundEventHandlerServiceImpl.java
Labels: ♻️ refactor

#302 #161 <Booking> 테스트 중 발견된 버그 수정
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/resources/application.yml
Labels: 🩹 fix

#307 #306 <Auth> log 추가 및 보상 트랜잭션 코드 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
Labels: 🩹 fix

#308 #303 <Review> 공통 로그 네이밍 적용
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/scheduler/AvgRatingBulkScheduler.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/scheduler/ReviewLikeScheduler.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewLikeServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/RedisRatingRepositoryImpl.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewLikeServiceTest.java
Labels: ♻️ refactor

#310 #309 <Payment> 모니터링 기능 추가
  com.taken_seat.payment-service/build.gradle
  com.taken_seat.payment-service/src/main/resources/application.yml
  com.taken_seat.payment-service/src/main/resources/logback-spring.xml
Labels: ❣feat, 👁️monitoring

#312 #311 <Review> 모니터링 기능 추가
  com.taken_seat.review-service/build.gradle
  com.taken_seat.review-service/src/main/resources/application.yml
  com.taken_seat.review-service/src/main/resources/logback-spring.xml
Labels: ❣feat, 👁️monitoring

#314 #313 <Gateway> BlackList 기능 추가 및 각 서비스의 exception을 반환하는 응답 핸들러 구현
  com.taken_seat.gateway-service/build.gradle
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/config/RedisConfig.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/exception/GlobalErrorHandler.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/exception/customException/BaseException.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/exception/customException/GatewayException.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/exception/enums/ResponseCode.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/filter/JwtAuthenticationFilter.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/util/JwtUtil.java
  com.taken_seat.gateway-service/src/main/resources/application.yml
Labels: ♻️ refactor

#318 #317 <Performance> 공연 시작 시간 조회 API 구현
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/response/PerformanceStartTimeDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
Labels: ❣feat

#320 #319 <Performance> 공연 도메인 Swagger 문서 적용
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/docs/PerformanceControllerDocs.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/controller/PerformanceHallController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/docs/PerformanceHallControllerDocs.java
  com.taken_seat.performance-service/src/main/resources/application.yml
Labels: ❣feat, 📝docs

#325 #321 <Performance> 공연 및 공연장 결합 제거 및 파사드 패턴 적용
  com.taken_seat.gateway-service/src/main/resources/application.yml
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/facade/PerformanceFacade.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/validator/PerformanceExistenceValidator.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/facade/PerformanceFacadeImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/facade/PerformanceHallFacade.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/validation/PerformanceHallExistenceValidator.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/facade/PerformanceHallFacadeImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performenceticket/application/service/PerformenceTicketService.java
Labels: ♻️ refactor, ❣feat, 🕹️ chore

#324 #323 <Common> docker.compose.yml 파일 수정
  com.taken_seat.common-service/docker-compose.common.yml
Labels: ♻️ refactor, 🕹️ chore

#328 #327 <DevOps> CI 빌드 후 GitHub Container Registry에 push 과정 추가
  .github/workflows/deploay.yml
Labels: ❣feat, 🕹️ chore

#329 #161 <Booking> 대기열 연계 기능 추가
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/response/SeatLayoutResponseDto.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingClientService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/client/PerformanceClient.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingClientServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingConsumer.java
  com.taken_seat.booking-service/src/main/resources/application.yml
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/QueueEnterMessage.java
Labels: ❣feat

#336 #330 <DevOps> Gateway yml 환경변수 수정
  com.taken_seat.gateway-service/src/main/resources/application.yml
Labels: ❣feat

#331 #326 <Performance> 공연 도메인 코드 리팩토링
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/helper/PerformanceUpdateHelper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/spec/PerformanceSpecification.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/validator/PerformanceValidator.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/spec/PerformanceHallSpecification.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/controller/PerformanceHallController.java
Labels: ♻️ refactor

#338 #246 <Performance> 공연 도메인 전체 조회 기능 QueryDSL 기반으로 리팩토링
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/Performanceticket/application/dto/mapper/RequestMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/Performanceticket/application/service/PerformanceTicketService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/Performanceticket/presentation/controller/PerformanceTicketController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/common/config/QueryDslConfig.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/common/support/QueryDslOrderUtil.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/ResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceQueryRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/spec/PerformanceSpecification.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceQueryRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/mapper/HallResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallQueryRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/spec/PerformanceHallSpecification.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallJpaRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallQueryRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallRepositoryImpl.java
Labels: ♻️ refactor, ❣feat, 🕹️ chore

#339 #330 <DevOps> 환경 변수 변경
  com.taken_seat.auth-service/src/main/resources/application.yml
  com.taken_seat.booking-service/src/main/resources/application.yml
  com.taken_seat.coupon-service/src/main/resources/application.yml
  com.taken_seat.payment-service/src/main/resources/application.yml
  com.taken_seat.performance-service/src/main/resources/application.yml
  com.taken_seat.queue-service/build.gradle
  com.taken_seat.queue-service/src/main/resources/application.yml
  com.taken_seat.review-service/src/main/resources/application.yml
Labels: ♻️ refactor

#340 README 파일을 만들었습니다.
  README.md
Labels: 📝docs

#341 각 서비스 하위 디렉토리에 Dockerfile을 추가했습니다.
  README.md
Labels: 📝docs

#343 #250 <Performance> 좌석 상태 변경 시 공연 회차 상태 자동 갱신
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/event/SeatStatusEventHandler.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/event/SeatStatusEventPublisher.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/event/SeatStatusChangedEvent.java
Labels: ❣feat

#344 Trouble shooting 추가했습니다
  README.md
Labels: 📝docs

#346 #345 <Gateway> BlackList 토큰의 저장시간을 access_token의 만료시간 만큼 저장할 수 있게 수정
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/filter/JwtAuthenticationFilter.java
Labels: ♻️ refactor

#350 #347 <Auth> 로그아웃 성공, 실패 단위 테스트
  com.taken_seat.auth-service/build.gradle
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthServiceImpl.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/AuthServiceTest.java
Labels: 🌼 test

#353 #349 <DevOps> 카프카 환경 변수 변경
  com.taken_seat.auth-service/src/main/resources/application.yml
  com.taken_seat.booking-service/src/main/resources/application.yml
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/config/KafkaConfig.java
  com.taken_seat.coupon-service/src/main/resources/application.yml
  com.taken_seat.payment-service/src/main/resources/application.yml
  com.taken_seat.performance-service/src/main/resources/application.yml
  com.taken_seat.queue-service/src/main/resources/application.yml
Labels: ❣feat

#355 #349 <DevOps> (FIX) Review kafka 설정 누락 추가
  com.taken_seat.review-service/src/main/resources/application.yml
Labels: 🩹 fix, ❣feat

#354 #352 <Auth> record 적용 및 코드 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthLoginDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthLoginResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthSignUpDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthSignUpResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/UserInfoResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/UserUpdateDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/auth/AuthController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/auth/AuthLoginRequestDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/auth/AuthSignUpRequestDto.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/AuthServiceTest.java
Labels: ♻️ refactor

#342 feat: #244 대기열 도메인 예외처리
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/customException/QueueException.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/application/dto/QueueReqDto.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/application/dto/TokenReqDto.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/application/dto/TokenResDto.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/application/service/QueueScheduler.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/application/service/QueueService.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/presentation/controller/QueueController.java
Labels: ♻️ refactor

#358 #356 <Mileage> 마일리지 DTO를 record로 변경
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/mileage/UserMileageDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/mileage/UserMileageResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/redis/RedisCacheConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/mileage/UserMileageRequestDto.java
Labels: ♻️ refactor

#361 #360 <Coupon> 코드 리팩토링 및 record 로 변경
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/CouponDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/CouponResponseDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/dto/CouponUpdateDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/CouponServiceImpl.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/repository/CouponRepository.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/redis/RedisCacheConfig.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/CouponController.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/dto/CreateCouponRequestDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/dto/UpdateCouponRequestDto.java
Labels: ♻️ refactor

#363 #351 <Performance> 공연 DTO 개선 및 Mapsturct 적용
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/response/PerformanceEndTimeDto.java
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/common/config/JacksonConfig.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/command/CreatePerformanceCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/command/CreatePerformanceScheduleCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/command/CreateSeatPriceCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/command/UpdatePerformanceCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/command/UpdatePerformanceScheduleCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/command/UpdateSeatPriceCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/PerformanceCreateCommandMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/PerformanceResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/PerformanceUpdateCommandMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/RequestMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/ResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/SearchFilterParam.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/UpdatePerformanceScheduleDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/UpdateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/request/UpdateSeatPriceDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/CreateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/DetailResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/PageResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/PerformanceScheduleResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/SearchResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/SeatPriceResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/response/UpdateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/helper/PerformanceCreateHelper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/helper/PerformanceUpdateHelper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceSchedule.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/PerformanceSeatPrice.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceQueryRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/validator/PerformanceValidator.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceQueryRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/docs/PerformanceControllerDocs.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/request/CreatePerformanceScheduleDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/request/CreateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/request/CreateSeatPriceDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/request/SearchFilterParam.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/request/UpdatePerformanceScheduleDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/request/UpdateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/request/UpdateSeatPriceDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/response/CreateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/response/DetailResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/response/PageResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/response/PerformanceScheduleResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/response/SearchResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/response/SeatPriceResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/response/UpdateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/mapper/HallRequestMapper.java
Labels: ♻️ refactor, ❣feat, 🕹️ chore

#371 #370 <DevOps> CD 과정 구현
  .github/workflows/ci_cd_deploy.yml
Labels: ❣feat

#372 #364 <Auth> 단위 테스트 및 코드 리팩토링
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/UserServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/user/UserQueryRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/vo/Role.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/persistence/user/UserQueryRepositoryImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/UserControllerDocs.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/AuthServiceTest.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/UserServiceTest.java
Labels: ♻️ refactor, 🌼 test

#365 #362 공연장 커맨드 기반 리팩토링 및 좌석 선점 API redisson 분산 락 적용
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/dto/request/BookingSeatClientRequestDto.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.gateway-service/src/main/resources/application.yml
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/command/CreatePerformanceHallCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/command/CreateSeatCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/command/UpdatePerformanceHallCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/command/UpdateSeatCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/mapper/HallCreateCommandMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/mapper/HallResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/mapper/HallUpdateCommandMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/request/SearchFilterParam.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/request/UpdateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/CreateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/DetailResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/PageResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/SearchResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/SeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/SeatLayoutResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/dto/response/UpdateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallClientService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallRedissonService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/application/service/PerformanceHallService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/helper/PerformanceHallCreateHelper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/PerformanceHall.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/model/Seat.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallQueryRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/repository/PerformanceHallRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/domain/validation/PerformanceHallValidator.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallQueryRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/infrastructure/repository/PerformanceHallRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/controller/PerformanceHallController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/controller/SeatRedissonController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/docs/PerformanceHallControllerDocs.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/request/BaseSeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/request/CreateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/request/CreateSeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/request/SearchFilterParam.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/request/UpdateRequestDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/request/UpdateSeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/response/CreateResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/response/DetailResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/response/PageResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/response/SearchResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/response/SeatDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/response/SeatLayoutResponseDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performancehall/presentation/dto/response/UpdateResponseDto.java
  com.taken_seat.performance-service/src/main/resources/application.yml
Labels: ♻️ refactor, ❣feat, 🕹️ chore

#374 #370 <DevOps> CD 과정 주석 처리
  .github/workflows/ci_cd_deploy.yml
Labels: 🕹️ chore

#379 #378 <Coupon> 쿠폰 단위 테스트 및 코드 리팩토링
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/application/service/CouponServiceImpl.java
  com.taken_seat.coupon-service/src/test/java/com/taken_seat/coupon_service/unit/CouponServiceTest.java
Labels: ♻️ refactor, 🌼 test

#385 #384 <Coupon> 권한 체킹에 AOP 활용해서 코드 리팩토링
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/entity/vo/Role.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/role/RoleCheck.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/role/aop/RoleCheckAspect.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/CouponController.java
Labels: ♻️ refactor

#389 #388 <Common> AOP 적용
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthSignUpDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthSignUpResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/UserInfoResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/UserUpdateDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/entity/user/User.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/persistence/user/UserQueryRepositoryImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/mileage/MileageController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/UserController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/auth/AuthSignUpRequestDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/user/UserUpdateRequestDto.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/AuthServiceTest.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/MileageServiceTest.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/UserServiceTest.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/aop/RoleCheckAspect.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/aop/annotation/RoleCheck.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/aop/vo/Role.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/entity/vo/Role.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/role/RoleCheck.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/role/aop/RoleCheckAspect.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/controller/CouponController.java
Labels: ♻️ refactor

#392 #387 <Payment> 코드 리팩터링 및 스웨거 적용
  com.taken_seat.payment-service/build.gradle
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/request/PaymentRegisterReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/request/PaymentUpdateReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/producer/PaymentRefundResponseProducer.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/kafka/producer/PaymentResponseProducer.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentRefundEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/config/swagger/SwaggerConfig.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/producer/PaymentRefundResponseProducerImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/producer/PaymentResponseProducerImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/JpaPaymentHistoryRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/PaymentHistoryJpaRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/PaymentHistoryRepositoryImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/PaymentJpaRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/PaymentRepositoryImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/swagger/PaymentSwaggerDocs.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
Labels: ♻️ refactor, ❣feat

#394 #393 <Auth> 코드 리팩토링
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/v2/UserMapper.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/mileage/MileageServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/v2/UserServiceV2.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/v2/UserServiceV2Impl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/security/WebSecurityConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/coupon/UserToCouponConsumerImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/v1/UserControllerV1.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/v2/UserControllerV2.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/user/v1/UserServiceV1Test.java
  com.taken_seat.gateway-service/src/main/resources/application.yml
Labels: ♻️ refactor, 🌼 test

#396 #395 <Payment> 코드 리팩터링 및 MapStruct 적용
  com.taken_seat.payment-service/build.gradle
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/request/PaymentRegisterReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/request/PaymentSearchReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/request/PaymentUpdateReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/response/PagePaymentResponseDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/response/PaymentDetailResDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/response/PaymentRegisterResDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/response/PaymentUpdateResDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/service/PaymentDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentQuerydslRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/config/redis/RedisCachingConfig.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/mapper/PaymentMapper.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/PaymentQuerydslRepositoryImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/main/resources/application.yml
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
Labels: ♻️ refactor, ❣feat

#399 #398 <Auth> 코드 리팩토링
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/auth/AuthSignUpResponseDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/v1/UserInfoResponseDtoV1.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/v1/UserMapper.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/dto/user/v2/UserInfoResponseDtoV2.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/v1/UserServiceV1Impl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/v2/UserServiceV2.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/v2/UserServiceV2Impl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/security/WebSecurityConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/auth/AuthController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/user/v2/UserControllerV2.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/AuthControllerDocs.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/auth/AuthServiceTest.java
  com.taken_seat.auth-service/src/test/java/com/taken_seat/auth_service/unit/user/v1/UserServiceV1Test.java
  com.taken_seat.gateway-service/src/main/resources/application.yml
Labels: ♻️ refactor, 🌼 test

#411 #410 <Auth> Swagger 기능 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/auth/AuthServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/service/user/v1/UserServiceV1Impl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/kafka/UserToCouponPublisherController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/AuthControllerDocs.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/UserControllerDocs.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/docs/UserToCouponPublisherControllerDocs.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/auth/AuthLoginRequestDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/auth/AuthSignUpRequestDto.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/dto/user/UserUpdateRequestDto.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
Labels: ♻️ refactor

#407 #397 <Review> 리팩터링 및 MapStruct 적용
  com.taken_seat.review-service/build.gradle
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/controller/request/ReviewRegisterReqDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/controller/request/ReviewUpdateReqDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/controller/response/PageReviewResponseDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/controller/response/ReviewDetailResDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/request/ReviewUpdateReqDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/response/ReviewDetailResDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/service/ReviewDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/dto/service/ReviewSearchDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewService.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/model/Review.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/ReviewQuerydslRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/ReviewRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/client/dto/PerformanceEndTimeDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/config/redis/RedisCachingConfig.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/config/swagger/SwaggerConfig.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/mapper/ReviewMapper.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/JpaReviewRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/PaymentRepositoryImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/ReviewJpaRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/ReviewQuerydslRepositoryImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/swagger/ReviewSwaggerDocs.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/presentation/controller/ReviewController.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewServicesTest.java
Labels: ♻️ refactor, ❣feat

#421 #420 <Common> kraft 모드 도입
  com.taken_seat.common-service/docker-compose.common.yml
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/dto/CreateCouponRequestDto.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/presentation/dto/UpdateCouponRequestDto.java
Labels: ♻️ refactor

#406 #405 <Performance> 공연 회차 삭제 API 구현
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/PerformanceResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/Performance.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/docs/PerformanceControllerDocs.java
Labels: ❣feat

#426 #425 <Review> 쿼리 인덱싱 추가
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/model/Review.java
Labels: ❣feat

#428 #427 <Payment> Search 기능에 DTO 변환 버그 수정
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/request/PaymentSearchReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/service/PaymentSearchDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentQuerydslRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/mapper/PaymentMapper.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/PaymentQuerydslRepositoryImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
Labels: 🩹 fix

#437 #436 <Performance> Kafka + Redis 기반 좌석 상태 변경 구조 및 DB 정합성 스케줄러 적용
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/PerformanceServiceApplication.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/common/config/KafkaConsumerConfig.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/common/config/KafkaProducerConfig.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/helper/SeatStatusKafkaHelper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/helper/SeatStatusRedisHelper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/scheduler/SeatStatusSyncScheduler.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceClientService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/model/ScheduleSeat.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceQueryRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/redis/SeatStatusRedisRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/kafka/consumer/SeatStatusConsumer.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/kafka/producer/SeatStatusChangedEvent.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/kafka/producer/SeatStatusProducer.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/redis/SeatStatusRedisRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceQueryRepositoryImpl.java
  com.taken_seat.performance-service/src/main/resources/application.yml
Labels: ♻️ refactor, ❣feat, 🕹️ chore

#443 feat : #442 DevOps CD 오픈
  .github/workflows/ci_cd_deploy.yml
Labels: ❣feat

#438 #161 <Booking> CQRS 패턴 도입
  README.md
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/command/BookingAdminPageReadCommand.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/command/BookingPageReadCommand.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/event/BookingEntityEvent.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/mapper/BookingMapper.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/dto/query/BookingStatusQuery.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingClientService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingCommandService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingConsumerService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingQueryService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/BenefitUsageHistory.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/BookingCommand.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/BookingQuery.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BookingAdminRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BookingCommandRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BookingQueryRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BookingRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingAdminJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingAdminRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingCommandJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingCommandRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingQueryJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingQueryRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingClientServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingCommandService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingCommandServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingConsumerServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingQueryService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingQueryServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/RedisExpireListener.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingClientController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingCommandController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingQueryController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/dto/response/AdminBookingPageResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/dto/response/AdminBookingReadResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/dto/response/BookingCreateResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/dto/response/BookingPageResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/dto/response/BookingReadResponse.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/config/RedisListenerConfig.java
  com.taken_seat.booking-service/src/main/resources/application.yml
  com.taken_seat.booking-service/src/test/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceTest.java
Labels: ❣feat

#440 #439 <Queue> 대기열 인원 중복 방지
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/application/service/QueueService.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/infrastructure/repository/QueueRepository.java
Labels: ❣feat

#444 #441 <README> 생성
  README.md
Labels: 📝docs

#448 리드미 수정 했습니다.
  README.md
Labels: 📝docs

#446 <DevOps> 모니터링 알림 설정을 위한 management.metrics.tags.service 추가
  com.taken_seat.auth-service/src/main/resources/application.yml
  com.taken_seat.booking-service/src/main/resources/application.yml
  com.taken_seat.coupon-service/src/main/resources/application.yml
  com.taken_seat.gateway-service/src/main/resources/application.yml
  com.taken_seat.payment-service/src/main/resources/application.yml
  com.taken_seat.performance-service/src/main/resources/application.yml
  com.taken_seat.queue-service/src/main/resources/application.yml
  com.taken_seat.review-service/src/main/resources/application.yml
Labels: 🕹️ chore

#447 #439 <Queue> 오류값 수정
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/application/service/QueueService.java
  com.taken_seat.queue-service/src/main/java/com/taken_seat/queue_service/presentation/controller/QueueController.java
Labels: 🩹 fix

#451 #161 <Booking> Dto 필드명 맞춤 및 Swagger 적용, 티켓 재발급 기능 추가
  com.taken_seat.booking-service/build.gradle
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingCommandService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/BookingController.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/dto/request/BookingCreateRequest.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/dto/request/BookingPayRequest.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/presentation/dto/response/SeatLayoutResponseDto.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/config/BookingSwaggerDocs.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/common/message/TicketRequestMessage.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/dto/request/TicketCreateRequest.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/application/service/TicketService.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/domain/repository/TicketRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/messaging/TicketKafkaConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/repository/TicketJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/repository/TicketRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/infrastructure/service/TicketServiceImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/presentation/TicketConsumer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/ticket/presentation/TicketController.java
  com.taken_seat.booking-service/src/main/resources/application.yml
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
Labels: ❣feat
