Repository toolatebro/TakenSeat, pull requests merged in 2025-05, with the labels that each got.

#453 #452 <Auth> token의 만료시간을 env로 관리
  com.taken_seat.auth-service/src/main/resources/application.yml
Labels: ♻️ refactor

#454 #445 <Payment> 토스 페이먼츠 결제 및 환불 API 구현
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentMessage.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/PaymentRefundMessage.java
  com.taken_seat.payment-service/build.gradle
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/client/TossPaymentClient.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/client/dto/TossCancelRequest.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/client/dto/TossConfirmResponse.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/client/dto/TossPaymentRequest.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/request/PaymentRegisterReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/request/PaymentUpdateReqDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/response/PaymentCheckoutResponse.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/service/PaymentDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentRefundEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/PaymentServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/enums/PaymentStatus.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/PaymentHistory.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/PaymentRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/client/TossPaymentClientImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/PaymentJpaRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/PaymentRepositoryImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/TossPaymentApiController.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/TossPaymentViewController.java
  com.taken_seat.payment-service/src/main/resources/application.yml
  com.taken_seat.payment-service/src/main/resources/static/style.css
  com.taken_seat.payment-service/src/main/resources/templates/tossPaymentCheckout.html
  com.taken_seat.payment-service/src/main/resources/templates/tossPaymentFail.html
  com.taken_seat.payment-service/src/main/resources/templates/tossPaymentSuccess.html
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
  com.taken_seat.review-service/build.gradle
Labels: ♻️ refactor, ❣feat

#458 #457 <Coupon> test코드 수정
  com.taken_seat.coupon-service/src/test/java/com/taken_seat/coupon_service/unit/CouponServiceTest.java
  com.taken_seat.review-service/build.gradle
Labels: 🌼 test

#460 #459 <Auth> 유저 10000명 생성
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/util/DataInitializer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/util/GenerateTokens.java
Labels: ♻️ refactor

#462 #461 <Auth> 유저 10000명 토큰 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/util/GenerateTokens.java
Labels: ♻️ refactor

#467 #466 <Payment> 코드 리팩터링 및 커맨드 디자인 패턴 적용
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/client/TossPaymentClient.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/command/PaymentCommand.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/command/api/DeletePaymentCommand.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/command/api/GetPaymentDetailCommand.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/command/api/RegisterPaymentCommand.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/command/api/SearchPaymentCommand.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/command/api/UpdatePaymentCommand.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/command/event/ProcessPaymentCommand.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/command/event/ProcessPaymentRefundCommand.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/dto/controller/response/PaymentDetailResDto.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/api/PaymentService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/api/PaymentServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/event/PaymentEventHandlerService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/event/PaymentEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/event/PaymentRefundEventHandlerService.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/event/PaymentRefundEventHandlerServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/tossclient/TossPaymentClient.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/tossclient/dto/TossCancelRequest.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/tossclient/dto/TossConfirmResponse.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/tossclient/dto/TossPaymentRequest.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/Payment.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/model/PaymentHistory.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/consumer/PaymentRefundRequestListenerImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/kafka/consumer/PaymentRequestListenerImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/tossclient/TossPaymentClientImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/TossPaymentApiController.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
Labels: ♻️ refactor, ❣feat

#470 #468 <Review> 커맨드 디자인 패턴 적용 및 코드 리팩터링
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/application/service/api/PaymentServiceImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/domain/repository/CustomPaymentQuerydslRepository.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/infrastructure/repository/CustomPaymentQuerydslRepositoryImpl.java
  com.taken_seat.payment-service/src/main/java/com/taken_seat/payment_service/presentation/controller/PaymentController.java
  com.taken_seat.payment-service/src/test/java/com/taken_seat/payment_service/unit/PaymentServiceTest.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/command/ReviewCommand.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/command/api/DeleteReviewCommand.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/command/api/GetReviewDetailCommand.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/command/api/RegisterReviewCommand.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/command/api/SearchReviewCommand.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/command/api/ToggleReviewLikeCommand.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/command/api/UpdateReviewCommand.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/scheduler/AvgRatingBulkScheduler.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewLikeService.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewLikeServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/CustomReviewQuerydslRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/CustomReviewQuerydslRepositoryImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/ReviewRepositoryImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/presentation/controller/ReviewController.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewLikeServiceTest.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewServicesTest.java
Labels: ♻️ refactor, ❣feat

#472 #464 <Coupon> Redisson + Lua 스크립트로 동시성 제어 및 단위 테스트
  com.taken_seat.coupon-service/build.gradle
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/redis/RedisLuaScriptConfig.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/redis/RedisOperationService.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/redis/RedisTemplateConfig.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/kafka/CouponToUserConsumerImpl.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/kafka/CouponToUserConsumerServiceImpl.java
  com.taken_seat.coupon-service/src/main/resources/lua/couponIssue.lua
  com.taken_seat.coupon-service/src/test/java/com/taken_seat/coupon_service/unit/CouponToUserConsumerServiceTest.java
Labels: ♻️ refactor, 🌼 test

#474 #473 <Auth> 쿠폰 만료시간 조건문 추가 및 coupon 생성 data.sql 수정
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/user/UserRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/dto/UserSnapshotEvent.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/scheduler/UserSnapshotScheduler.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/exception/enums/ResponseCode.java
  com.taken_seat.coupon-service/src/main/resources/db/data.sql
Labels: ♻️ refactor

#475 #469 <Performance> 추천 서비스 Kafka 이벤트 구현
  com.taken_seat.performance-service/build.gradle
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/common/config/KafkaConsumerConfig.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/common/config/KafkaProducerConfig.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/facade/PerformanceFacade.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/PerformanceRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/facade/PerformanceFacadeImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/repository/PerformanceRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceClientController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/request/RecommendedPerformanceDto.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/application/command/RecommendRegisterCommand.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/application/service/RecommendMatrixService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/application/service/RecommendQueryService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/domain/facade/RecommendFacade.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/facade/RecommendFacadeImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/kafka/consumer/BookingCompletedListener.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/kafka/consumer/RecommendRequestListener.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/kafka/consumer/UserSnapshotListener.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/kafka/dto/BookingCompletedMessage.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/kafka/dto/RecommendRequestMessage.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/kafka/dto/UserSnapshotEvent.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/redis/RecommendationCacheService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/scheduler/RecommendRequestScheduler.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/presentation/dto/response/RecommendedPerformanceResponseDto.java
Labels: ♻️ refactor, ❣feat

#477 feat: #476 [Booking] 사용자의 공연 예매 횟수 기능 추가
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/application/service/BookingProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/domain/repository/BookingCommandRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/messaging/BookingKafkaProducer.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingCommandJpaRepository.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/repository/BookingCommandRepositoryImpl.java
  com.taken_seat.booking-service/src/main/java/com/taken_seat/booking_service/booking/infrastructure/service/BookingCommandService.java
  com.taken_seat.booking-service/src/main/resources/application.yml
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/BookingCompletedMessage.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/common/config/KafkaConsumerConfig.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/infrastructure/kafka/consumer/BookingCompletedListener.java
Labels: ❣feat

#480 #479 <Performance> 유저 스냅샷 Kafka 발행/수신 오류 및 추천 테스트 API 구성
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/user/UserRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/config/security/WebSecurityConfig.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/presentation/controller/kafka/UserToCouponPublisherController.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/scheduler/UserSnapshotScheduler.java
  com.taken_seat.auth-service/src/main/resources/application.yml
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/common/config/KafkaConsumerConfig.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceClientController.java
Labels: 🩹 fix

#483 #478 <Auth> 코드 리팩토링
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/domain/repository/userCoupon/UserCouponRepository.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/scheduler/UserCouponScheduler.java
Labels: ♻️ refactor

#486 #418 <Performance> 주간 공연 랭킹 조회 기능 구현
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/dto/mapper/PerformanceResponseMapper.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceClientService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/application/service/PerformanceService.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/domain/repository/redis/PerformanceRankingRedisRepository.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/infrastructure/redis/PerformanceRankingRedisRepositoryImpl.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/controller/PerformanceController.java
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/performance/presentation/dto/response/PerformanceRankingResponseDto.java
Labels: ❣feat

#485 #484 <Coupon> 코드 리팩토링
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/aop/MetricTimerAspect.java
  com.taken_seat.common-service/src/main/java/com/taken_seat/common_service/message/KafkaUserInfoMessage.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/domain/entity/Coupon.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/config/MetricConfig.java
  com.taken_seat.coupon-service/src/main/java/com/taken_seat/coupon_service/infrastructure/kafka/CouponToUserConsumerServiceImpl.java
  com.taken_seat.coupon-service/src/main/resources/application.yml
  com.taken_seat.coupon-service/src/main/resources/db/data.sql
  com.taken_seat.coupon-service/src/main/resources/lua/couponIssue.lua
  com.taken_seat.coupon-service/src/test/java/com/taken_seat/coupon_service/unit/CouponToUserConsumerServiceTest.java
Labels: ♻️ refactor

#488 #487 <Auth> 쿠폰 사용량 추적
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/booking/UserToBookingConsumer.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/application/kafka/booking/UserToBookingConsumerService.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerImpl.java
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/kafka/booking/UserToBookingConsumerServiceImpl.java
  com.taken_seat.auth-service/src/main/resources/application.yml
Labels: ♻️ refactor, 👁️monitoring

#493 #490 <Gateway> 성능 약간 개선?
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/config/RedisConfig.java
  com.taken_seat.gateway-service/src/main/java/com/taken_seat/gateway_service/filter/JwtAuthenticationFilter.java
Labels: ♻️ refactor

#492 #491 <Performance> 추천 로직 테스트 및 로깅 추가
  com.taken_seat.performance-service/src/main/java/com/taken_seat/performance_service/recommend/application/service/RecommendMatrixService.java
  com.taken_seat.performance-service/src/test/java/com/taken_seat/performance_service/recommend/application/service/RecommendMatrixServiceTest.java
Labels: 🌼 test

#489 #471 <Review> 리뷰 변경 감지 기반 평점 캐싱 갱신 기능 구현
  com.taken_seat.auth-service/src/main/java/com/taken_seat/auth_service/infrastructure/util/DataInitializer.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/scheduler/AvgRatingBulkScheduler.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewChangeMaker.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/application/service/ReviewServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/RedisRatingRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/domain/repository/ReviewRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/client/dto/PerformanceEndTimeDto.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/redis/service/ReviewChangeMakerImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/redis/service/ReviewLikeServiceImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/RedisRatingRepositoryImpl.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/ReviewJpaRepository.java
  com.taken_seat.review-service/src/main/java/com/taken_seat/review_service/infrastructure/repository/ReviewRepositoryImpl.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewLikeServiceTest.java
  com.taken_seat.review-service/src/test/java/com/taken_seat/review_service/unit/ReviewServicesTest.java
Labels: ♻️ refactor, ❣feat
